# Generated by Django 3.2.7 on 2021-09-14 08:38

from django.db import migrations, models
import django_extensions.db.fields
import uuid


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Request',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('x_created', django_extensions.db.fields.CreationDateTimeField(auto_now_add=True, verbose_name='x_created')),
                ('x_modified', django_extensions.db.fields.ModificationDateTimeField(auto_now=True, verbose_name='x_modified')),
                ('requester_name', models.CharField(max_length=64, verbose_name='Requester name')),
                ('sleepover_date', models.DateField(verbose_name='Sleepover date')),
                ('num_persons', models.IntegerField(verbose_name='Number of persons')),
                ('accepted', models.BooleanField(default=False, verbose_name='Accepted')),
            ],
        ),
    ]
