# Generated by Django 3.2.7 on 2021-09-16 17:03

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('form', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='request',
            name='sleepover_date',
        ),
        migrations.AddField(
            model_name='request',
            name='coitus',
            field=models.BooleanField(default=False, verbose_name='Is coitus'),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='request',
            name='estimated_coitus_time',
            field=models.BooleanField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='request',
            name='sleepover_date_from',
            field=models.DateField(default=datetime.date(2021, 9, 16), verbose_name='Sleepover date from'),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='request',
            name='sleepover_date_to',
            field=models.DateField(default=datetime.date(2021, 9, 16), verbose_name='Sleepover date to'),
            preserve_default=False,
        ),
    ]
