# Generated by Django 3.2.7 on 2021-09-16 17:14

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('form', '0002_auto_20210916_1903'),
    ]

    operations = [
        migrations.AlterField(
            model_name='request',
            name='estimated_coitus_time',
            field=models.TimeField(blank=True, null=True),
        ),
    ]
