# Generated by Django 3.2.7 on 2021-09-16 17:59

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('form', '0003_alter_request_estimated_coitus_time'),
    ]

    operations = [
        migrations.AlterField(
            model_name='request',
            name='num_persons',
            field=models.CharField(max_length=4, verbose_name='Number of persons'),
        ),
    ]
