# Generated by Django 3.2.7 on 2021-09-16 18:25

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('form', '0005_auto_20210916_2018'),
    ]

    operations = [
        migrations.AlterField(
            model_name='request',
            name='requester_name',
            field=models.CharField(blank=True, max_length=64, null=True, verbose_name='Requester name'),
        ),
    ]
