# Generated by Django 3.2.7 on 2021-09-16 18:44

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('form', '0006_alter_request_requester_name'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='request',
            name='estimated_coitus_time',
        ),
        migrations.AddField(
            model_name='request',
            name='estimated_coitus_time_end',
            field=models.TimeField(blank=True, null=True, verbose_name='Estimated coitus time start'),
        ),
        migrations.AddField(
            model_name='request',
            name='estimated_coitus_time_start',
            field=models.TimeField(blank=True, null=True, verbose_name='Estimated coitus time start'),
        ),
    ]
