# Generated by Django 3.2.7 on 2021-09-16 18:46

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('form', '0007_auto_20210916_2044'),
    ]

    operations = [
        migrations.AlterField(
            model_name='request',
            name='num_persons',
            field=models.CharField(blank=True, max_length=4, null=True, verbose_name='Number of persons'),
        ),
    ]
